api_login_check:
    path: /api/login
api_refresh_token:
    path: /api/token/refresh
api_token_invalidate:
    path: /api/token/invalidate
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /api
